## https://www.datacamp.com/community/tutorials/decision-trees-R

## @ param expression.data is a normalised HTseq count file, filterd on only the genes of intrest. The samples are in the first row.
## @ param information.table dataframe containing per sample information (diagnosis, over-expression positive or negative of genes of intrest) and color linked to that information.

##Generate PCA information.
expression.data.pca <- prcomp(expression.data, center = TRUE, scale. = TRUE)
summary(expression.data.pca)

library(rpart)
library(tree)

diagnosis <- information.table$diagnosis

total.expression.data.pca <- data.frame(expression.data.pca$x[,1:5], diagnosis)

View(total.expression.data.pca)

## Tree build with all samples
tree.total.expression.data.pca <- tree(diagnosis~., data=total.expression.data.pca)
summary(tree.total.expression.data.pca)
plot(tree.total.expression.data.pca)
text(tree.total.expression.data.pca, pretty = 0)

## make training and test set of the samples. 
set.seed(101)
trainset.expression.data.pca <- sample(1:nrow(total.expression.data.pca), 60)

## make a tree based on the 60 training samples
tree.trainset.expression.data.pca <- tree(diagnosis~., total.expression.data.pca, subset = trainset.expression.data.pca)

plot(tree.trainset.expression.data.pca)
text(tree.trainset.expression.data.pca, pretty = 0)
summary(tree.trainset.expression.data.pca)

## Prediction with prediction set on the training tree, generated by the 60 trainging samples.
tree.predictset.expression.data.pca <- predict(tree.trainset.expression.data.pca, total.expression.data.pca[-trainset.expression.data.pca,], type = "class")
with(total.expression.data.pca[-trainset.expression.data.pca,], table(tree.predictset.expression.data.pca, diagnosis))

## Pruning and cross validation. 
cv.trainset.expression.data.pca <- cv.tree(tree.trainset.expression.data.pca, FUN = prune.misclass)
plot(cv.trainset.expression.data.pca)

## use the number of nodes based on the cross validation
prune.tree.trainset.expression.data.pca <- prune.misclass(tree.trainset.expression.data.pca, best = 6)
plot(prune.tree.trainset.expression.data.pca)
text(prune.tree.trainset.expression.data.pca, pretty = 0)

## predict again with the prediction samples
tree.predictset.expression.data.pca <- predict(prune.tree.trainset.expression.data.pca, total.expression.data.pca[-trainset.expression.data.pca,], type = "class")
with(total.expression.data.pca[-trainset.expression.data.pca,], table(tree.predictset.expression.data.pca, diagnosis))
summary(tree.predictset.expression.data.pca)


